pipeline:
  tests:
    image: node:8
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn lint
      - yarn flow
      - yarn build
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    secrets: [ docker_username, docker_password, sentry_auth_key ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args_from_env:
      - sentry_auth_key
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
